### ISSUE TITLE
Why not exclude vendor libraries?

### ISSUE THREAD

**Issue by erne-mt** [cubbles/bde#4]
Hi,

I just updatet bower dependencies a bit and I noticed that we did not exclude the vendor files from git tracking.

Was this intentional or was it missed somehow?

**Comment by pwrinc** [comment]
Hi,

we explicitely decided to take bower dependencies under version control. Reason for this is explained here: http://stackoverflow.com/questions/17186377/why-check-in-bower-components/17208939#17208939

**Comment by erne-mt** [comment]
Ok, than we might need to roll back `commit a7838283dd15f5b901529a6f9a6515c38a9cd37e`.
