### ISSUE TITLE
What does the custom-validator element do?

### ISSUE THREAD

**Issue by erne-mt** [cubbles/bde#5]
There is a BDE element _custom-validator_.

But in code it does not seem to do something, is it depricated or is it intented to do something and it is just not finished yet?

[see here](https://github.com/cubbles/bde/tree/master/webpackages/bde/bde/elements/custom-validator)

**Comment by jtrs** [comment]
It is unnecessary indeed. It was intended for validate a jason value in textarea (in manifest.webpackage init array, or propery-editor) but this is integrated in bde-explorer.details.html. The validaton in textarea do not work until now. See https://github.com/PolymerElements/paper-input/issues/414
