### ISSUE TITLE
iframe  has not the correct dimensions in bde-application-view

### ISSUE THREAD

**Issue by jtrs** [cubbles/bde#7]
The integrated iframe has no attributes for define height and width.
In Chrome have a fix height 805x150 (maybe default dimensions?)
![grafik.png](https://images.zenhubusercontent.com/5a7d58ce4b5806bc2bc6448d/08c5f96f-d28f-4b2e-aae3-5f7051e5517c)
In Firefox works correct.

Option1:  Add a fullscreen dimension oriented in view-height and view-width (minus bde-frame)
Option2: Add functionality like in rte/iframe rte/frame-resizer, wich change the iframe dimensions depends on iner document dimensions

**Comment by pwrinc** [comment]
@jtrs: Please merge final changes into  `BDE_ODIN` branch before closing this issue

**Comment by edwingamboa** [comment]
Style associated to `bde-application-view` wasn't being correctly applied, since its `style` element was outside `template` element.
The `style` definition was correctly located.

**Comment by jtrs** [comment]
cherry-picked to BDE_ODIN branch
